language: go
sudo: false

go: 
- 1.5.1
- 1.5.2
- tip

matrix:
  allow_failures:
    - go: tip

script:
- (if [ "$(goimports -d .)" == "" ]; then echo "Good format"; else echo "Bad format"; exit 33; fi);
- (if [ "$(goimports -d .)" == "" ]; then echo "Good format"; else echo "Bad format"; exit 33; fi);
- go vet ./...
- go test -v ./...